/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author realinfo
 */
public class EChangepassword extends javax.swing.JInternalFrame {

    
    String username;

    public EChangepassword(String username) {
        initComponents();
        this.username = username;
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        setSize(1920, 1080);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtoldpass = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtconfirmpass = new javax.swing.JTextField();
        txtnewpass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Change Password");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Old Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        txtoldpass.setBackground(new java.awt.Color(0, 0, 0));
        txtoldpass.setForeground(new java.awt.Color(255, 255, 255));
        txtoldpass.setBorder(null);
        jPanel2.add(txtoldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 180, -1));

        btnupdate.setBackground(new java.awt.Color(255, 255, 0));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("New Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Confirm Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        txtconfirmpass.setBackground(new java.awt.Color(0, 0, 0));
        txtconfirmpass.setForeground(new java.awt.Color(255, 255, 255));
        txtconfirmpass.setBorder(null);
        jPanel2.add(txtconfirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 180, -1));

        txtnewpass.setBackground(new java.awt.Color(0, 0, 0));
        txtnewpass.setForeground(new java.awt.Color(255, 255, 255));
        txtnewpass.setBorder(null);
        jPanel2.add(txtnewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 180, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 180, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 222, 190, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 180, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 292, 180, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try {
            String oldpassword = txtoldpass.getText();
            String newpassword = txtnewpass.getText();
            String confirmpassword = txtconfirmpass.getText();

            if (newpassword.equals(confirmpassword)) {
                Class.forName("oracle.jdbc.OracleDriver");
                String str = "jdbc:oracle:thin:@localhost:1521:";
                Connection con = DriverManager.getConnection(str, "project", "12345");

                String sql1 = "select * from employee where username=?";
                PreparedStatement ps1 = con.prepareStatement(sql1);
                ps1.setString(1, username);

                ResultSet rs = ps1.executeQuery();
                String op = "";
                if (rs.next()) {
                    op = rs.getString("password");
                }

                if(op.equals(oldpassword))
                {
                String sql = "update employee set password=? where username=?";
                PreparedStatement ps = con.prepareStatement(sql);

                ps.setString(1, newpassword);
                ps.setString(2, username);

                int count = ps.executeUpdate();
                if (count > 0) {
                    JOptionPane.showMessageDialog(this, "passowrd changed !!!");

                }
                }
                else {
                JOptionPane.showMessageDialog(this, "old password is incorrect!!");

            }
            } else {
                JOptionPane.showMessageDialog(this, "password doesn't match!!");

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtconfirmpass;
    private javax.swing.JTextField txtnewpass;
    private javax.swing.JTextField txtoldpass;
    // End of variables declaration//GEN-END:variables
}
