/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author project mahajan
 */
public class EditEmployee extends javax.swing.JInternalFrame {

    /**
     * Creates new form student
     */
    public EditEmployee() {
        initComponents();
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        showData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txteid = new javax.swing.JTextField();
        empid = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        salary = new javax.swing.JLabel();
        txtsal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txthire = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadd = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        designation = new javax.swing.JLabel();
        idesignation = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rbsingle = new javax.swing.JRadioButton();
        rbmarried = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        pwd = new javax.swing.JLabel();
        txtpwd = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 490, 380));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txteid.setBackground(new java.awt.Color(240, 240, 240));
        txteid.setBorder(null);
        jPanel1.add(txteid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, -1));

        empid.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        empid.setText("EmpId");
        jPanel1.add(empid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 20));

        name.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        name.setText("Name");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 40, 20));

        txtname.setBackground(new java.awt.Color(240, 240, 240));
        txtname.setBorder(null);
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 230, -1));

        gender.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        gender.setText("Gender");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, -1));

        buttonGroup1.add(rbmale);
        rbmale.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rbmale.setText("Male");
        jPanel1.add(rbmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 60, -1));

        buttonGroup1.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rbfemale.setText("Female");
        jPanel1.add(rbfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, -1));

        salary.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        salary.setText("Salary");
        jPanel1.add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, -1));

        txtsal.setBackground(new java.awt.Color(240, 240, 240));
        txtsal.setBorder(null);
        jPanel1.add(txtsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setText("Hire Date");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 50, -1));

        txthire.setBackground(new java.awt.Color(240, 240, 240));
        txthire.setBorder(null);
        jPanel1.add(txthire, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 20));

        address.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        address.setText("Address");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 80, -1));

        txtadd.setColumns(20);
        txtadd.setRows(5);
        jScrollPane1.setViewportView(txtadd);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, 80));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setText("(dd-mon-yyyy)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 52, 230, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, 230, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, 230, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtemail.setBackground(new java.awt.Color(240, 240, 240));
        txtemail.setBorder(null);
        jPanel2.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 230, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setText("Email");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        designation.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        designation.setText("Designation");
        jPanel2.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        idesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Project Manager", "Team Leader", "Team Member" }));
        idesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idesignationActionPerformed(evt);
            }
        });
        jPanel2.add(idesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 230, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setText("Contact No.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtcontact.setBackground(new java.awt.Color(240, 240, 240));
        txtcontact.setBorder(null);
        jPanel2.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("Marital Status");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        buttonGroup2.add(rbsingle);
        rbsingle.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rbsingle.setText("Single");
        jPanel2.add(rbsingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        buttonGroup2.add(rbmarried);
        rbmarried.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        rbmarried.setText("Married");
        rbmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmarriedActionPerformed(evt);
            }
        });
        jPanel2.add(rbmarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setText("Date of Birth");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtdob.setBackground(new java.awt.Color(240, 240, 240));
        txtdob.setBorder(null);
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        jPanel2.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, -1));

        user.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        user.setText("Username");
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtuser.setBackground(new java.awt.Color(240, 240, 240));
        txtuser.setBorder(null);
        jPanel2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 230, -1));

        pwd.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        pwd.setText("Password");
        jPanel2.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtpwd.setBackground(new java.awt.Color(240, 240, 240));
        txtpwd.setBorder(null);
        jPanel2.add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 240, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel6.setText("(dd-mon-yyyy)");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 80, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 172, 230, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 222, 230, 0));

        jSeparator8.setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 272, 230, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 240, 20));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 230, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 290, 380));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        save.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 90, 40));

        modify.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        modify.setText("Modify");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });
        jPanel3.add(modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 100, 40));

        Delete.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel3.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 100, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1100, 70));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Manage Employee");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1100, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        deleteData();
    }

    private void btnModify1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        modifyData();
    }

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        saveData();
    }

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtMarksActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code hint row = table.getSelectedRow();
        TableModel z = table.getModel();

        int row = table.getSelectedRow();
        String eid = (String) z.getValueAt(row, 0);
        String name = (String) z.getValueAt(row, 1);
        String gender = (String) z.getValueAt(row, 2);
        String sal = (String) z.getValueAt(row, 3);
        String hiredate = (String) z.getValueAt(row, 4);
        String address = (String) z.getValueAt(row, 5);
        String email = (String) z.getValueAt(row, 6);
        String designation = (String) z.getValueAt(row, 7);
        String dob = (String) z.getValueAt(row, 8);
        String contact = (String) z.getValueAt(row, 9);
        String marital = (String) z.getValueAt(row, 10);
        String user = (String) z.getValueAt(row, 11);
        String pwd = (String) z.getValueAt(row, 12);

        txteid.setText(eid);
        txtname.setText(name);
        txtcontact.setText(contact);
        txtsal.setText(sal);
        txtuser.setText(user);
        txtpwd.setText(pwd);
        txthire.setText(hiredate);
        txtadd.setText(address);
        txtemail.setText(email);
        if (marital.equalsIgnoreCase("single")) {
            rbsingle.setSelected(true);
        } else {
            rbmarried.setSelected(true);
        }

        if (gender.equalsIgnoreCase("male")) {
            rbmale.setSelected(true);
        } else {
            rbfemale.setSelected(true);
        }
        txtdob.setText(dob);
        idesignation.setSelectedItem(designation);


    }//GEN-LAST:event_tableMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        saveData();        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        modifyData();        // TODO add your handling code here:
    }//GEN-LAST:event_modifyActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        deleteData();        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void rbmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmarriedActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    private void idesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idesignationActionPerformed

   

    void showData() {

        try {

            Vector h = new Vector();
            h.add("EmpId");
            h.add("Name");
            h.add("Gender");
            h.add("Salary");
            h.add("Hire Date");
            h.add("Address");
            h.add("Email");
            h.add("Designation");
            h.add("Date of Birth");
            h.add("Contact No.");
            h.add("Marital Status");
            h.add("Username");
            h.add("Password");

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");
            String q = "select * from employee";
            PreparedStatement y = x.prepareStatement(q);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {
                eid = rs.getString("EmpId");
                name = rs.getString("Name");
                gender = rs.getString("Gender");
                sal = rs.getString("Salary");
                hiredate = rs.getString("Hire_Date");
                SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
                    java.util.Date dx1=f1.parse(hiredate);
                f1=new SimpleDateFormat("dd-MMM-yyyy");
                hiredate=f1.format(dx1);
                address = rs.getString("Address");
                email = rs.getString("Email");
                designation = rs.getString("Designation");
                dob=rs.getString("Date_of_Birth");
               
                SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
                    java.util.Date dx=f.parse(dob);
                f=new SimpleDateFormat("dd-MMM-yyyy");
                dob=f.format(dx);
                 
                contact = rs.getString("Contact");
                marital = rs.getString("Marital_Status");
                user = rs.getString("Username");
                pwd = rs.getString("Password");

                Vector r = new Vector();
                r.add(eid);
                r.add(name);
                r.add(gender);
                r.add(sal);
                r.add(hiredate);
                r.add(address);
                r.add(email);
                r.add(designation);
                r.add(dob);
                r.add(contact);
                r.add(marital);
                r.add(user);
                r.add(pwd);

                //inserted into data
                d.add(r);
            }
            y.close();
            x.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            table.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void saveData() {
        try {
            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            eid = txteid.getText();
            name = txtname.getText();
            if(!Validation.isValidName(name))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Name");
                return;
            }
            sal = txtsal.getText();
            email = txtemail.getText();
            if(!Validation.isValidEmail(email))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Email");
                return;
            }
            hiredate = txthire.getText();
            contact = txtcontact.getText();
            if(contact.length()>10)
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Contact Number");
                return;
            }

            if (rbmale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }
            if (rbsingle.isSelected()) {
                marital = "single";
            } else {
                marital = "married";
            }
            address = txtadd.getText();
            designation = (String) idesignation.getSelectedItem();
            dob=txtdob.getText();
            user = txtuser.getText();
            pwd = txtpwd.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "insert into Employee values(?,?,?,?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, eid);
            y.setString(2, name);
            y.setString(3, sal);
            y.setString(4, designation);
            y.setString(5, hiredate);
            y.setString(6, email);
            y.setString(7, contact);
            y.setString(8, gender);
            y.setString(9, dob);
            y.setString(10, address);
            y.setString(11, marital);
            y.setString(12, user);
            y.setString(13, pwd);
            

            int n = y.executeUpdate();
            String d = n + " data inserted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void modifyData() {
        try {
            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            eid = txteid.getText();
            name = txtname.getText();
            if(!Validation.isValidName(name))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Name");
                return;
            }
            sal = txtsal.getText();
            email = txtemail.getText();
            if(!Validation.isValidEmail(email))
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Email");
                return;
            }
            hiredate = txthire.getText();
            contact = txtcontact.getText();
            if(contact.length()>10)
            {
                JOptionPane.showMessageDialog(this,"Please Enter Valid Contact Number");
                return;
            }

            if (rbmale.isSelected()) {
                gender = "male";
            } else {
                gender = "female";
            }
            if (rbsingle.isSelected()) {
                marital = "single";
            } else {
                marital = "married";
            }
            address = txtadd.getText();
            designation = (String) idesignation.getSelectedItem();
            dob = txtdob.getText();
            user = txtuser.getText();
            pwd = txtpwd.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "update Employee set name=?,salary=?,gender=?,address=?,designation=?,contact=?,email=?,date_of_birth=?,marital_status=?,username=?,password=?,hire_date=? where empid=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(13, eid);
            y.setString(1, name);
            y.setString(2, sal);
            y.setString(5, designation);
            y.setString(12, hiredate);
            y.setString(7, email);
            y.setString(6, contact);
            y.setString(3, gender);
            y.setString(8, dob);
            y.setString(4, address);
            y.setString(9, marital);
            y.setString(10, user);
            y.setString(11, pwd);

            int n = y.executeUpdate();
            String d = n + " data updated";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void deleteData() {
        try {
            String eid;
            eid = txteid.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "delete from employee where empid=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, eid);

            int n = y.executeUpdate();
            String d = n + " data deleted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void clearData() {
        txteid.setText("");
        txtname.setText("");
        txtcontact.setText("");
        txtsal.setText("");
        txtuser.setText("");
        txtpwd.setText("");
        txthire.setText("");
        txtadd.setText("");
        txtemail.setText("");
        rbsingle.setSelected(true);
        rbmale.setSelected(true);
        txtdob.setText("");
        idesignation.setSelectedIndex(0);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel designation;
    private javax.swing.JLabel empid;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox idesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton modify;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pwd;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JRadioButton rbmarried;
    private javax.swing.JRadioButton rbsingle;
    private javax.swing.JLabel salary;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtadd;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txteid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthire;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpwd;
    private javax.swing.JTextField txtsal;
    private javax.swing.JTextField txtuser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
