/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nikhil
 */
public class myprojects extends javax.swing.JInternalFrame {
String username;
    /**
     * Creates new form Task
     */
String empid;
    public myprojects(String username,String empid) {
        initComponents();
        setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
        this.username=username;
        this.empid=empid;
        showData();
    }

    void setData() {

        try {

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");
            String q = "select * from project";
            PreparedStatement y = x.prepareStatement(q);

            ResultSet rs = y.executeQuery();

            String pid, ptitle, stdate, edate, md, des;
            while (rs.next()) {
                pid = rs.getString("Project_Id");
                ptitle = rs.getString("project_title");
                stdate = rs.getString("start_date");
                edate = rs.getString("end_date");
                md = rs.getString("modules");
                des = rs.getString("description");

                txtpid.setText(pid);
                txttitle.setText(ptitle);
                txtmd.setText(md);
                txtstartdate.setText(stdate);
                txtenddate.setText(edate);
                txtdes.setText(des);

            }
            y.close();
            x.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void showData() {

        try {

            Vector h = new Vector();
            h.add("Assign_Id");
            h.add("Employee_Id");
            h.add("Project_Id");
            h.add("Status");

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");
            String q = "select * from project_assign where empid=?";
            
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, empid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String assignid, empid, pid, status;
            while (rs.next()) {
                assignid = rs.getString("assign_id");
                empid = rs.getString("empid");
                pid = rs.getString("project_id");
                status = rs.getString("status");

                Vector R = new Vector();
                R.add(assignid);
                R.add(empid);

                R.add(pid);
                R.add(status);

                //inserted into data
                d.add(R);
            }
            y.close();
            x.close();
            DefaultTableModel z = new DefaultTableModel(d, h);
            table.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdes = new javax.swing.JTextArea();
        txtpid = new javax.swing.JTextField();
        txtmd = new javax.swing.JTextField();
        txttitle = new javax.swing.JTextField();
        startdate = new javax.swing.JLabel();
        enddate = new javax.swing.JLabel();
        txtenddate = new javax.swing.JTextField();
        txtstartdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 440, 660));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdes.setEditable(false);
        txtdes.setColumns(20);
        txtdes.setRows(5);
        jScrollPane3.setViewportView(txtdes);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 250, 110));

        txtpid.setEditable(false);
        jPanel1.add(txtpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 30));

        txtmd.setEditable(false);
        jPanel1.add(txtmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 250, 30));

        txttitle.setEditable(false);
        jPanel1.add(txttitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 30));

        startdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        startdate.setText("Start Date ");
        jPanel1.add(startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 20));

        enddate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enddate.setText("End Date");
        jPanel1.add(enddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 20));

        txtenddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenddateActionPerformed(evt);
            }
        });
        jPanel1.add(txtenddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 250, 30));
        jPanel1.add(txtstartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 250, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("(dd-mon-yyyy)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("(dd-mon-yyyy)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Project Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 90, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Project Title");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Modules");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Description");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 300, 450));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("My Projects");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenddateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
     

        try {
            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");
            TableModel z = table.getModel();
            
            int row = table.getSelectedRow();
            String projectid = (String) z.getValueAt(row, 2);
            
            String q = "select * from project where project_id=?";
            
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1,projectid);
            ResultSet rs = y.executeQuery();
            while(rs.next())
            {
                
                
                
                String pid = rs.getString("project_id");
                String ptitle = rs.getString("project_title");
                
                String stdate = rs.getString("start_date");
                String enddate = rs.getString("end_date");
                String md = rs.getString("modules");
                String des = rs.getString("description");
                
                txtpid.setText(pid);
                txttitle.setText(ptitle);
                txtstartdate.setText(stdate);
                txtenddate.setText(enddate);
                txtmd.setText(md);
                
                txtdes.setText(des);}
            y.close();
            x.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enddate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel startdate;
    private javax.swing.JTable table;
    private javax.swing.JTextArea txtdes;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtmd;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtstartdate;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables

}
