/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nikhil
 */
public class Task extends javax.swing.JInternalFrame {

    /**
     * Creates new form Task
     */
    public Task() {
        initComponents();
         setResizable(true);
        setMaximizable(true);
        setIconifiable(true);
        setClosable(true);
         showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        pid = new javax.swing.JTextField();
        md = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        startdate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        enddate = new javax.swing.JLabel();
        txtenddate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        des.setColumns(20);
        des.setRows(5);
        jScrollPane3.setViewportView(des);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 80));
        jPanel1.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 30));
        jPanel1.add(md, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 30));
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Project Id");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Project Title");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Modules");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Description");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, -1));

        startdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        startdate.setText("Start Date ");
        jPanel1.add(startdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 70, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("(dd-mon-yyyy)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 10));
        jPanel1.add(txtstartdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 30));

        enddate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enddate.setText("End Date");
        jPanel1.add(enddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, 20));

        txtenddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenddateActionPerformed(evt);
            }
        });
        jPanel1.add(txtenddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 210, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("(dd-mon-yyyy)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 10));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 80, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Modify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 100, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 470, 440));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("Manage Project");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel2.add(jScrollPane2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 540, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveData(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtenddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenddateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modifyData();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
 TableModel z = table.getModel();

        int row = table.getSelectedRow();
        String Project_ID = (String) z.getValueAt(row, 0);
        String Project_TITTLE = (String) z.getValueAt(row, 1);
        String START_DATE = (String) z.getValueAt(row, 2);
        String END_DATE = (String) z.getValueAt(row, 3);
        String MODULES = (String) z.getValueAt(row, 4);
       
        String DESCRIPTION = (String) z.getValueAt(row, 5);
       
         pid.setText(Project_ID);  
        title.setText(Project_TITTLE);       
        txtstartdate.setText(START_DATE);
        txtenddate.setText(END_DATE);
        md.setText(MODULES);
       
        des.setText(DESCRIPTION);
    }//GEN-LAST:event_tableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        deleteData();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea des;
    private javax.swing.JLabel enddate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField md;
    private javax.swing.JTextField pid;
    private javax.swing.JLabel startdate;
    private javax.swing.JTable table;
    private javax.swing.JTextField title;
    private javax.swing.JTextField txtenddate;
    private javax.swing.JTextField txtstartdate;
    // End of variables declaration//GEN-END:variables

    void saveData() {
        try {
            String  Project_ID,Project_TITLE, START_DATE, END_DATE, MODULES, DESCRIPTION,STATUS="pending";
            Project_ID = pid.getText();
            Project_TITLE = title.getText();
            START_DATE = txtstartdate.getText();
            END_DATE = txtenddate.getText();
            MODULES =md.getText();
            
           

           

            DESCRIPTION = des.getText();
            

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "insert into Project values(?,?,?,?,?,?,?)";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, Project_ID);
            y.setString(2, Project_TITLE);
            
            y.setString(3, START_DATE);
            y.setString(4, END_DATE);
            y.setString(5, MODULES);
         
            y.setString(7, STATUS);

            y.setString(6, DESCRIPTION);

            int n = y.executeUpdate();
            String d = n + " data inserted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);
            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();

        }
    }

    void modifyData() {
        try {
            String Project_ID ,Project_TITLE, START_DATE, END_DATE, MODULES, DESCRIPTION;
            Project_ID = pid.getText();
            Project_TITLE = title.getText();
            START_DATE = txtstartdate.getText();
            END_DATE = txtenddate.getText();
            MODULES = md.getText();

            

            DESCRIPTION = des.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "update project set  Project_TITLE=?, START_DATE=?, END_DATE=?, MODULES=?,  DESCRIPTION=? where project_id=? ";

            PreparedStatement y = x.prepareStatement(q);

             y.setString(6, Project_ID);

            y.setString(1, Project_TITLE);

            y.setString(2, START_DATE);
            y.setString(3, END_DATE);
            y.setString(4, MODULES);
           
            y.setString(5, DESCRIPTION);

            int n = y.executeUpdate();
            String d = n + " data updated";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);
            

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

    void clearData() {
        pid.setText("");
        title.setText("");
        txtenddate.setText("");
        txtstartdate.setText("");
      
        des.setText("");

        md.setText("");

    }

    void showData() {

        try {

            Vector h = new Vector();
            h.add("Project_Id");
            h.add("Project_Title");
            h.add("Start_Date");
            h.add("End_Date");
            
            h.add("Modules");
            h.add("Description");
            h.add("Status");

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");
            String q = "select * from Project";
            PreparedStatement y = x.prepareStatement(q);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String pid,title,startdate,enddate,md,des,status;
            while (rs.next()) {
                pid= rs.getString("Project_ID");
                title = rs.getString("Project_TITLE");
                startdate = rs.getString("START_DATE");
                SimpleDateFormat f1=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
                    java.util.Date dx1=f1.parse(startdate);
                f1=new SimpleDateFormat("dd-MMM-yyyy");
                startdate=f1.format(dx1);
                enddate = rs.getString("END_DATE");
                SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
                    java.util.Date dx=f.parse(enddate);
                f=new SimpleDateFormat("dd-MMM-yyyy");
                
                enddate=f.format(dx);
                md = rs.getString("MODULES");
                des = rs.getString("DESCRIPTION");
                status=rs.getString("Status");

                Vector R = new Vector();
                R.add(pid);
                R.add(title);
                
                R.add(startdate);
               R.add(enddate);
                R.add(md);
                R.add(des);
                R.add(status);

                //inserted into data
                d.add(R);
            }
            y.close();
            x.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            table.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }
    void deleteData() {
        try {
            String Project_ID;
            Project_ID = pid.getText();

            Class.forName("oracle.jdbc.OracleDriver");
            String str = "jdbc:oracle:thin:@localhost:1521:";
            Connection x = DriverManager.getConnection(str, "project", "12345");

            String q = "delete from Project where Project_ID=?";

            PreparedStatement y = x.prepareStatement(q);

            y.setString(1, Project_ID);

            int n = y.executeUpdate();
            String d = n + " data deleted";

            y.close();

            x.close();

            JOptionPane.showMessageDialog(this, d);

            showData();
            clearData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());

            ex.printStackTrace();
        }
    }

}
