/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author realinfo
 */
public class viewTeamStatus extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewTeamStatus
     */
    String empid;
    Connection x;

    public viewTeamStatus(String empid) {
        initComponents();

        try {
            Class.forName("oracle.jdbc.OracleDriver");

            String str = "jdbc:oracle:thin:@localhost:1521:";
            x = DriverManager.getConnection(str, "project", "12345");
        } catch (Exception ex) {
            Logger.getLogger(viewTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.empid = empid;
        viewProjects();
    }

    void viewProjects() {

        try {

            String q = "select * from project_assign,project where empid=? and project_assign.status='Pending' and project.project_id=project_assign.project_id";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, empid);
            ResultSet rs = y.executeQuery();
            while (rs.next()) {

                MyData my = new MyData();
                my.pid = rs.getString("project_id");
                my.title = rs.getString("project_Title");

                cmbprojects.addItem(my);

            }
            y.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void viewTeamMembers(String teamid) {
        JOptionPane.showMessageDialog(this, teamid);
        try {

            Vector h = new Vector();
            h.add("Emp Id");
            h.add("name");
            h.add("Email");
            h.add("Contact");

            String q = "select * from team_members,employee where team_id=? and team_members.emp_id=employee.empid";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, teamid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("empid"));
                r.add(rs.getString("name"));
                r.add(rs.getString("email"));
                r.add(rs.getString("contact"));
              

                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable1.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void viewModules(String projectid) {

        try {

            Vector h = new Vector();
            h.add("Module Id");
            h.add("Module ");

            String q = "select * from modules where project_id=?";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, projectid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("module_id"));
                r.add(rs.getString("module_name"));

                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable5.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        cmbprojects = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtsubdate = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Projects");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 80, 30));

        jPanel1.add(cmbprojects, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 320, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Team Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText("Date of Creation");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("Status");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team leader Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Emp Id");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setText("Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel12.setText("Email");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel13.setText("Contact No");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel15.setText("jLabel15");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel16.setText("jLabel16");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel17.setText("jLabel17");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, 160));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team Members", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 580, 100));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -70, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 600, 130));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modules Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 90));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 600, 130));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Description");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        jScrollPane2.setViewportView(txtdescription);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 320, 80));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date of Submission");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        txtsubdate.setEditable(false);
        jPanel7.add(txtsubdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 240, 30));

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel7.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 100, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 600, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed

        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("dd-MMM-yy");
        String cdate = sd.format(d);

        txtsubdate.setText(cdate);

        MyData my = (MyData) cmbprojects.getSelectedItem();
        String projectid = my.pid;
        String teamleader = "";
        String teamid = "";
        String asid="";
         try {
             JOptionPane.showMessageDialog(this, "PPP : "+projectid);
         String qx = "select * from project_assign where project_id=?";
            PreparedStatement yx = x.prepareStatement(qx);
            yx.setString(1, projectid);
            ResultSet rsx = yx.executeQuery();
            if (rsx.next()) {
                asid = rsx.getString("assign_id");
            }
            
            JOptionPane.showMessageDialog(this, "AAA : "+asid);
       
            String q1 = "select * from team where assignid=?";
            PreparedStatement y1 = x.prepareStatement(q1);
            y1.setString(1, asid);
            ResultSet rs1 = y1.executeQuery();
            if (rs1.next()) {
                teamid = rs1.getString("team_id");
                jLabel7.setText(rs1.getString("team_id"));
                jLabel8.setText(rs1.getString("date_of_creation"));
                jLabel9.setText(rs1.getString("status"));
                teamleader = rs1.getString("team_leader");
            }

            String q2 = "select * from employee where empid=?";
            PreparedStatement y2 = x.prepareStatement(q2);
            y2.setString(1, teamleader);
            ResultSet rs2 = y2.executeQuery();
            if (rs2.next()) {

                jLabel14.setText(rs2.getString("empid"));
                jLabel15.setText(rs2.getString("name"));
                jLabel16.setText(rs2.getString("email"));
                jLabel17.setText(rs2.getString("contact"));

            }

            viewTeamMembers(teamid);
            viewModules(projectid);

        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed

        MyData my = (MyData) cmbprojects.getSelectedItem();
        String projectid = my.pid;
        String assignid = "";
        try {
            String q2 = "select * from project_assign where project_id=?";
            PreparedStatement y2 = x.prepareStatement(q2);
            y2.setString(1, projectid);
            ResultSet rs2 = y2.executeQuery();
            if (rs2.next()) {
                assignid = rs2.getString("assign_id");
            }
            String description = txtdescription.getText();
            String subdate = txtsubdate.getText();

            String q3 = "insert into projectsubmission (assignid,dateofsubmission,description) values(?,?,?)";
            PreparedStatement y3 = x.prepareStatement(q3);
            y3.setString(1, assignid);
            y3.setString(2, subdate);
            y3.setString(3, description);
           int chk= y3.executeUpdate();
            
            
            
             String q4 = "update project_assign set status='closed' where assign_id=?";
            PreparedStatement y4 = x.prepareStatement(q4);
            y4.setString(1, assignid);
         
            y4.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Project Submitted Succesfully!!!");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox cmbprojects;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtsubdate;
    // End of variables declaration//GEN-END:variables
}
