/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author realinfo
 */
public class viewModulesStatus extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewModulesStatus
     */
    Connection x;
    String empid;

    public viewModulesStatus(String empid) {
        initComponents();

        try {
            Class.forName("oracle.jdbc.OracleDriver");

            String str = "jdbc:oracle:thin:@localhost:1521:";
            x = DriverManager.getConnection(str, "project", "12345");
        } catch (Exception ex) {
            Logger.getLogger(viewTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.empid = empid;
        viewTeams();

    }

    void viewTeams() {

        try {

            String q = "select * from team where team_leader=? and status='Pending'";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, empid);
            ResultSet rs = y.executeQuery();
            while (rs.next()) {

                MyData4 my = new MyData4();
                my.tid = rs.getString("team_id");
                my.tname = rs.getString("date_of_creation");

                cmbteam.addItem(my);

            }
            y.close();

          

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void viewTableData(String teamid) {

        try {

            Vector h = new Vector();
            h.add("Emp Id");
            h.add("Name");
            h.add("Module Id");
            h.add("Module");
            h.add("Assign Date");
            h.add("Submission Date");
            h.add("Status");

            String q2 = "select * from team_members,moduleassign,modules,employee where team_id=? and moduleassign.empid=team_members.emp_id and modules.module_id=moduleassign.moduleid and employee.empid=team_members.emp_id";
            PreparedStatement y = x.prepareStatement(q2);
            y.setString(1, teamid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("emp_id"));
                r.add(rs.getString("name"));
                r.add(rs.getString("module_id"));
                r.add(rs.getString("module_name"));
                r.add(rs.getString("dateofassign"));
                r.add(rs.getString("dateofsubmission"));
                r.add(rs.getString("status"));

                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable1.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbteam = new javax.swing.JComboBox();
        btnsearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnsubmit = new javax.swing.JButton();
        txtsubmissiondate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Team ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.add(cmbteam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 210, 40));

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 380, 100));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 840, 140));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel3.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 40));

        txtsubmissiondate.setEditable(false);
        jPanel3.add(txtsubmissiondate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Project Submission Date");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 440, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        Date d = new Date();
        SimpleDateFormat sd = new SimpleDateFormat("dd-MMM-yy");
        String cdate = sd.format(d);

        txtsubmissiondate.setText(cdate);

        MyData4 my = (MyData4) cmbteam.getSelectedItem();
        String teamid = my.tid;

        viewTableData(teamid);


    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed

        
        int c=0;
                for(int i=0;i<jTable1.getRowCount();i++)
                {
                    String s=(String)jTable1.getValueAt(i,6);
                    if(!s.equalsIgnoreCase("submit"))
                    {
                        c=1;
                        break;
                    }
                }
                
        if(c==0)
        {
        MyData4 my = (MyData4) cmbteam.getSelectedItem();
        String teamid = my.tid;

        String submissiondate = txtsubmissiondate.getText();
        try {
            String q3 = "insert into teamsubmission (teamid,dateofsubmission) values (?,?)";
            PreparedStatement y3 = x.prepareStatement(q3);
            y3.setString(1, teamid);
            y3.setString(2, submissiondate);

            int chk = y3.executeUpdate();
            if (chk > 0) {
                JOptionPane.showMessageDialog(this, "Submitted Successfully!!");
            }
            
            
            String q4 = "update team set status='closed' where team_id=?";
            PreparedStatement y4 = x.prepareStatement(q4);
            y4.setString(1, teamid);
            y4.executeUpdate();
            viewTeams();;

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "All Modules sholud be submit to submit your project!!!");
                        
        }
    }//GEN-LAST:event_btnsubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox cmbteam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtsubmissiondate;
    // End of variables declaration//GEN-END:variables
}
