/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author realinfo
 */
public class viewModules extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewModules
     */
    String empid;
    Connection x;

    String massignid;

    public viewModules(String empid) {
        initComponents();
        try {
            Class.forName("oracle.jdbc.OracleDriver");

            String str = "jdbc:oracle:thin:@localhost:1521:";
            x = DriverManager.getConnection(str, "project", "12345");
        } catch (Exception ex) {
            Logger.getLogger(viewTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.empid = empid;
        viewAssignedModules();
        viewPreviousAssignedModules();
    }

    void viewAssignedModules() {

        try {

            Vector h = new Vector();
            h.add("Module Id ");
            h.add("Module");
            h.add("Description");
            h.add("Status");
            h.add("Assign Date");
            h.add("Submission Date");
            h.add("Assign Id");

            String q = "select * from moduleassign,modules where moduleassign.empid=? and modules.module_id=moduleassign.moduleid and massignid not in (select massignid from modulesubmission)";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, empid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("module_id"));
                r.add(rs.getString("module_name"));
                r.add(rs.getString("description"));
                r.add(rs.getString("status"));
                r.add(rs.getString("dateofassign"));
                r.add(rs.getString("dateofsubmission"));
                r.add(rs.getString("massignid"));
                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable1.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    
    void viewPreviousAssignedModules() {

        try {

            Vector h = new Vector();
            h.add("Module Id ");
            h.add("Module");
            h.add("Description");
            h.add("Status");
            h.add("Assign Date");
            h.add("Submission Date");
            h.add("Assign Id");

            String q = "select * from moduleassign,modules where moduleassign.empid=? and modules.module_id=moduleassign.moduleid and massignid in (select massignid from modulesubmission)";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, empid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("module_id"));
                r.add(rs.getString("module_name"));
                r.add(rs.getString("description"));
                r.add(rs.getString("status"));
                r.add(rs.getString("dateofassign"));
                r.add(rs.getString("dateofsubmission"));
                r.add(rs.getString("massignid"));
                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable2.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtdateofsub = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 660, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 690, 160));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Module ID ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Module Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("Description");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setText("Date of Assign");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setText("Submission Date");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel8.setText("Status");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel12.setText("jLabel12");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel14.setText("jLabel14");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel15.setText("jLabel15");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jLabel17.setText("jLabel17");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 330, 230));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Date of Submission");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtdateofsub.setEditable(false);
        txtdateofsub.setBackground(new java.awt.Color(204, 204, 255));
        txtdateofsub.setBorder(null);
        jPanel3.add(txtdateofsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 270, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Submission Details");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtdescription.setColumns(20);
        txtdescription.setRows(5);
        jScrollPane3.setViewportView(txtdescription);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 70));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 100, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 270, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 340, 230));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 650, 110));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 670, 150));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 255, 255));
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 255));
        jLabel10.setText("VIEW MODULES");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

//          r.add(rs.getString("module_id"));0
//                r.add(rs.getString("module_name"));1
//                r.add(rs.getString("description"));2
//                r.add(rs.getString("status"));3
//                r.add(rs.getString("dateofassign"));4
//                 r.add(rs.getString("dateofsubmission"));5
        int row = jTable1.getSelectedRow();
        TableModel tm = jTable1.getModel();
        jLabel12.setText(String.valueOf(tm.getValueAt(row, 0)));
        jLabel13.setText(String.valueOf(tm.getValueAt(row, 1)));
        jLabel14.setText(String.valueOf(tm.getValueAt(row, 2)));
        jLabel17.setText(String.valueOf(tm.getValueAt(row, 3)));
        jLabel15.setText(String.valueOf(tm.getValueAt(row, 4)));
        jLabel16.setText(String.valueOf(tm.getValueAt(row, 5)));

        massignid = String.valueOf(tm.getValueAt(row, 6));
         Date d = new Date();
            SimpleDateFormat sd = new SimpleDateFormat("dd-MMM-yy");
            String cdate = sd.format(d);
        
        txtdateofsub.setText(cdate);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String dateofsubmission = txtdateofsub.getText();
            String description = txtdescription.getText();

            String q = "insert into modulesubmission (massignid,dateofsubmission,descripiton) values (?,?,?)";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, massignid);
            y.setString(2, dateofsubmission);
            y.setString(3, description);
            int chk = y.executeUpdate();
            
            
            
             String q1 = "update moduleassign set status='submit' where massignid=?";
            PreparedStatement y1 = x.prepareStatement(q1);
            y1.setString(1, massignid);
          
             y1.executeUpdate();
            
            
            if (chk > 0) {
                JOptionPane.showMessageDialog(this, "Module Submit Successfully!!!");
            }
            
             viewAssignedModules();
        viewPreviousAssignedModules();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtdateofsub;
    private javax.swing.JTextArea txtdescription;
    // End of variables declaration//GEN-END:variables
}
