/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import project.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author realinfo
 */
public class viewTeam extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewTeam
     */
    String empid;
    Connection x;
    String teamid;

    public viewTeam(String empid) {
        initComponents();
        try {
            Class.forName("oracle.jdbc.OracleDriver");

            String str = "jdbc:oracle:thin:@localhost:1521:";
            x = DriverManager.getConnection(str, "project", "12345");
        } catch (Exception ex) {
            Logger.getLogger(viewTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.empid = empid;
        viewTeams();

    }

    void viewTeams() {

        try {

            Vector h = new Vector();
            h.add("Team Id");
            h.add("Date of Creation");
            h.add("Status");

            String q = "select * from team where team_leader=?";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, empid);
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("team_id"));
                r.add(rs.getString("date_of_creation"));
                r.add(rs.getString("status"));

                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable1.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    void viewAssignedData() {

        try {

            Vector h = new Vector();
            h.add("Assign ID");
            h.add("Module Id");
            h.add("Emp Id");
            h.add("Status");
            h.add("Date");

            String q = "select * from moduleassign where moduleid in (select module_id from modules where project_id=?)";
            PreparedStatement y = x.prepareStatement(q);
            y.setString(1, jLabel2.getText());
            ResultSet rs = y.executeQuery();

            Vector d = new Vector();

            String eid, name, gender, sal, address, email, designation, dob, contact, marital, user, pwd, hiredate;
            while (rs.next()) {

                Vector r = new Vector();

                r.add(rs.getString("massignid"));
                r.add(rs.getString("moduleid"));
                r.add(rs.getString("empid"));
                r.add(rs.getString("status"));
                r.add(rs.getString("dateofassign"));

                //inserted into data
                d.add(r);
            }
            y.close();

            DefaultTableModel z = new DefaultTableModel(d, h);
            jTable2.setModel(z);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error " + ex.getMessage());
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        labelprojectid = new javax.swing.JLabel();
        labelprojectname = new javax.swing.JLabel();
        labelmodules = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cmbmodules = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbmembers = new javax.swing.JComboBox();
        btnassign = new javax.swing.JButton();
        txtdateofsubmission = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 260));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 480, 300));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelprojectid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelprojectid.setText("Project Id: ");
        jPanel3.add(labelprojectid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        labelprojectname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelprojectname.setText("Project Name: ");
        jPanel3.add(labelprojectname, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 67, -1, -1));

        labelmodules.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelmodules.setText("Modules: ");
        jPanel3.add(labelmodules, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Description: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 490, 240));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbmodules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmodulesActionPerformed(evt);
            }
        });
        jPanel4.add(cmbmodules, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Modules");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Team Members");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel4.add(cmbmembers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, 30));

        btnassign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnassign.setText("Assign");
        btnassign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnassignActionPerformed(evt);
            }
        });
        jPanel4.add(btnassign, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, -1));

        txtdateofsubmission.setBackground(new java.awt.Color(204, 204, 255));
        txtdateofsubmission.setBorder(null);
        jPanel4.add(txtdateofsubmission, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Date of Submission");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel9.setText("(dd-MMM-YY)");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 490, 300));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Team Members", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel5.setToolTipText("");
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 200));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 480, 240));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("jLabel10");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 5, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 255));
        jLabel11.setText("View Team");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 110, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbmodulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmodulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmodulesActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row = jTable1.getSelectedRow();
        TableModel tm = jTable1.getModel();
        teamid = (String) tm.getValueAt(row, 0);
        try {
            String q1 = "select * from team,project,project_assign where project.project_id=project_assign.project_id and team.assignid=project_assign.assign_id and team.team_id=?";
            PreparedStatement y1 = x.prepareStatement(q1);
            y1.setString(1, teamid);
            ResultSet rs1 = y1.executeQuery();
            while (rs1.next()) {
                jLabel2.setText(rs1.getString("project_id"));
                jLabel3.setText(rs1.getString("project_title"));
                jLabel4.setText(rs1.getString("modules"));
                jLabel5.setText(rs1.getString("description"));
            }
            cmbmodules.removeAllItems();
            String q2 = "select * from modules where project_id=?";
            PreparedStatement y2 = x.prepareStatement(q2);
            y2.setString(1, jLabel2.getText());
            ResultSet rs2 = y2.executeQuery();
            while (rs2.next()) {
                MyData3 m = new MyData3();
                m.mid = rs2.getString("module_id");
                m.mname = rs2.getString("module_name");

                cmbmodules.addItem(m);
            }

            cmbmembers.removeAllItems();
            String q3 = "select * from team_members,employee where team_members.emp_id=employee.empid and team_members.team_id=? and employee.designation='Team Member'";
            PreparedStatement y3 = x.prepareStatement(q3);
            y3.setString(1, teamid);
            ResultSet rs3 = y3.executeQuery();
            while (rs3.next()) {
                MyData1 m = new MyData1();
                m.empid = rs3.getString("emp_id");
                m.ename = rs3.getString("name");

                cmbmembers.addItem(m);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

viewAssignedData();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnassignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnassignActionPerformed

        try {
            String dateofsubmission=txtdateofsubmission.getText();
            MyData3 m = (MyData3) cmbmodules.getSelectedItem();
            String moduleid = m.mid;

            MyData1 m1 = (MyData1) cmbmembers.getSelectedItem();
            String eid = m1.empid;

            Date d = new Date();
            SimpleDateFormat sd = new SimpleDateFormat("dd-MMM-yy");
            String cdate = sd.format(d);

            String q3 = "insert into moduleassign (moduleid,empid,status,dateofassign,dateofsubmission) values (?,?,?,?,?)";
            PreparedStatement y3 = x.prepareStatement(q3);
            y3.setString(1, moduleid);
            y3.setString(2, eid);
            y3.setString(3, "assigned");
            y3.setString(4, cdate);
              y3.setString(5, dateofsubmission);
            int chk = y3.executeUpdate();
            if (chk > 0) {
                JOptionPane.showMessageDialog(this, "Module Assigned Successfully!!");
            }
            viewAssignedData();

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnassignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnassign;
    private javax.swing.JComboBox cmbmembers;
    private javax.swing.JComboBox cmbmodules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelmodules;
    private javax.swing.JLabel labelprojectid;
    private javax.swing.JLabel labelprojectname;
    private javax.swing.JTextField txtdateofsubmission;
    // End of variables declaration//GEN-END:variables
}
